apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: testpod1
  name: testpod1
spec:
  minReadySeconds: 10
  strategy:
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 0
  replicas: 6
  selector:
    matchLabels:
      app: testpod1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: testpod1
    spec:
      containers:
      - image: kiran2361993/kubegame:v2
        name: kubegame
      - image: kiran2361993/mydb:v1
        name: mysqldb
