apiVersion: v1
kind: Secret 
metadata:
  name: aws-access-keys
type: Opaque 
data:
  AWS_ACCESS_KEY_ID: QUtJQTZHQk1HMzZJU1FSQllEVEw=
  AWS_SECRET_ACCESS_KEY: RXFFNGc0QU8wdG5mRzhiVTdCZEpHbFdQdnpIWVRZOC9GUlRnWDhwcg==

