
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: awscli-deployment
  name: awscli-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: awscli-deployment
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: awscli-deployment
    spec:
      containers:
      - image: kiran2361993/troubleshootingtools:v1
        name: troubleshootingtools
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws-access-keys # refrenced from secrets.yaml
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-access-keys # refrenced from secrets.yaml
                key: AWS_SECRET_ACCESS_KEY
          - name: AWS_DEFAULT_REGION
            value: "us-east-1"



