apiVersion: v1 
kind: Secret 
metadata:
  name: aws-creds-in-file
type: Opaque 
stringData:
  credentials: |
    [default]
    aws_access_key_id = AKIA6GBMG36I5OTFSZOB
    aws_secret_access_key = 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
