apiVersion: v1 
kind: Secret 
metadata:
  name: aws-creds-in-file
type: Opaque 
stringData:
  credentials: |
    [default]
    aws_access_key_id = <access-key>
    aws_secret_access_key = <secret-access-key>