apiVersion: v1 
kind: Pod 
metadata: 
  name: secret-test-pod 
spec: 
  containers:
  - name: aws-cli-container 
    image: kiran2361993/troubleshootingtools:v1 
    volumeMounts: 
      - name: secret-volume 
        mountPath: /root/.aws/credentials 
        subPath: credentials
        readOnly: true 

  volumes: 
    - name: secret-volume
      secret: 
        secretName: aws-creds-in-file