apiVersion: v1
kind: Pod
metadata:
  labels:
    run: alpha1
  name: alpha1
  namespace: alpha
spec:
  containers:
  - image: kiran2361993/kubegame:v2
    name: alpha1

---

kind: Pod
metadata:
  labels:
    run: alpha2
  name: alpha2
  namespace: alpha2
spec:
  containers:
  - image: kiran2361993/kubegame:v2
    name: alpha2