
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app1
  name: app1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app1
    spec:
      containers:
      - image: kiran2361993/kubegame:v2
        name: kubegame
        readinessProbe:
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10 
        livenessProbe:
          httpGet:
            path: /index.html 
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20


