apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMrRENDQWVDZ0F3SUJBZ0lNR0FRaW0xdlREenhuVno4U01BMEdDU3FHU0liM0RRRUJDd1VBTUJneEZqQVUKQmdOVkJBTVREV3QxWW1WeWJtVjBaWE10WTJFd0hoY05NalF4TURNeE1URXhOalEzV2hjTk16UXhNRE14TVRFeApOalEzV2pBWU1SWXdGQVlEVlFRREV3MXJkV0psY201bGRHVnpMV05oTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGCkFBT0NBUThBTUlJQkNnS0NBUUVBbGVRTGFBRlFYbVNQTERMVjdabWxmMDJNUDVLK3NOa2Q4Z1Q3ZTBrQVFSeisKeHUzdkc4MWVnVytkZ3luS0VSREFYc1hQY0JuaU5GZVF1REZNQTJIeFZQbi9pT0RkQ2trUWgzTUNXdndHYWkvVgp5UzhWMjBSNStRVVNTUWNIVEU2YmJheWJFWDhXZ2lseHBodFZGSWtHVUp0Y05mZUw0WUNOLzJaNnZLRUNpbWw0CmRybTJXeHkzNGNTbkpVc3VrK2V3N2ZWZHVkMmVlUXpXRWd1b2RQS3EwRisyanpVVWFvamlLbG9EelB4akluc2gKT0FSSUtRRTI4Zjluam9iUk90OUNYK2cvUGd2Q1Q2MzQwUTFxaWNZdHJKUkhvb2Q5cHFzRzJ4Ryt5R2FEY21VTQp5Yk1BSGRtTzRZS1NhWEJNbEUyT1RhZzdrOE9KQVJoQytjdWs3aDVtRHdJREFRQUJvMEl3UURBT0JnTlZIUThCCkFmOEVCQU1DQVFZd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVVFON0NkZnlNamxoejdoaHYKNWxzWXVPNjlSa0V3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUFUNkRwNkpPZWE1Y2R2YmVOUzdPYWMwUVBORgpOTVNQSWlEOUtSQk9wYjZqeldRRFdybGltQk0ySlZUQ1BjWlNtNmx3dTVyWnZBUFM2bzBuZXpuc1ZDTDhHa205Cm00U3RXZW5QdlhhenM1OEJhd3pqU1l4N0RRSGVaMkg3WU5uSDVDR0xCcUE1VTROYVdXQjFrdG94ZjJpNEk5TjMKSFpvM3FQbmRuY1pydmc4MmsyVnRxYytvOGxxVDFtN2dHQjduSGVwdmRCSkdPL2REeWpJajJoSGdhODVHSjlQRQptbFRSZlAvTWhnT1RSZ3lBYU5Na0lGZW4yV3BrNTlISGg5ekxjME5JSmpEK2dRUjVwUXhtUWtBdlV4Slk0dHVGCm91NHovY2FFVmNrNjBTUHBJa2dyU2pJMk1oTDJzcGhCWFRaU2V5S3J2TkJta2xyVXB5dXY5dGdpMkpFPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://api.cloudadhanik.xyz
    tls-server-name: api.internal.cloudadhanik.xyz
  name: cloudadhanik.xyz
contexts:
- context:
    cluster: cloudadhanik.xyz
    namespace: development
    user: user1
  name: cloudadhanik.xyz
current-context: user1-context
kind: Config
users:
- name: user1
  user:
    client-certificate: path to .crt
    client-key: path to .key

--- 

apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMrRENDQWVDZ0F3SUJBZ0lNR0FRaW0xdlREenhuVno4U01BMEdDU3FHU0liM0RRRUJDd1VBTUJneEZqQVUKQmdOVkJBTVREV3QxWW1WeWJtVjBaWE10WTJFd0hoY05NalF4TURNeE1URXhOalEzV2hjTk16UXhNRE14TVRFeApOalEzV2pBWU1SWXdGQVlEVlFRREV3MXJkV0psY201bGRHVnpMV05oTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGCkFBT0NBUThBTUlJQkNnS0NBUUVBbGVRTGFBRlFYbVNQTERMVjdabWxmMDJNUDVLK3NOa2Q4Z1Q3ZTBrQVFSeisKeHUzdkc4MWVnVytkZ3luS0VSREFYc1hQY0JuaU5GZVF1REZNQTJIeFZQbi9pT0RkQ2trUWgzTUNXdndHYWkvVgp5UzhWMjBSNStRVVNTUWNIVEU2YmJheWJFWDhXZ2lseHBodFZGSWtHVUp0Y05mZUw0WUNOLzJaNnZLRUNpbWw0CmRybTJXeHkzNGNTbkpVc3VrK2V3N2ZWZHVkMmVlUXpXRWd1b2RQS3EwRisyanpVVWFvamlLbG9EelB4akluc2gKT0FSSUtRRTI4Zjluam9iUk90OUNYK2cvUGd2Q1Q2MzQwUTFxaWNZdHJKUkhvb2Q5cHFzRzJ4Ryt5R2FEY21VTQp5Yk1BSGRtTzRZS1NhWEJNbEUyT1RhZzdrOE9KQVJoQytjdWs3aDVtRHdJREFRQUJvMEl3UURBT0JnTlZIUThCCkFmOEVCQU1DQVFZd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVVFON0NkZnlNamxoejdoaHYKNWxzWXVPNjlSa0V3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUFUNkRwNkpPZWE1Y2R2YmVOUzdPYWMwUVBORgpOTVNQSWlEOUtSQk9wYjZqeldRRFdybGltQk0ySlZUQ1BjWlNtNmx3dTVyWnZBUFM2bzBuZXpuc1ZDTDhHa205Cm00U3RXZW5QdlhhenM1OEJhd3pqU1l4N0RRSGVaMkg3WU5uSDVDR0xCcUE1VTROYVdXQjFrdG94ZjJpNEk5TjMKSFpvM3FQbmRuY1pydmc4MmsyVnRxYytvOGxxVDFtN2dHQjduSGVwdmRCSkdPL2REeWpJajJoSGdhODVHSjlQRQptbFRSZlAvTWhnT1RSZ3lBYU5Na0lGZW4yV3BrNTlISGg5ekxjME5JSmpEK2dRUjVwUXhtUWtBdlV4Slk0dHVGCm91NHovY2FFVmNrNjBTUHBJa2dyU2pJMk1oTDJzcGhCWFRaU2V5S3J2TkJta2xyVXB5dXY5dGdpMkpFPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://api.cloudadhanik.xyz
    tls-server-name: api.internal.cloudadhanik.xyz
  name: cloudadhanik.xyz
contexts:
- context:
    cluster: cloudadhanik.xyz
    namespace: production
    user: user2
  name: cloudadhanik.xyz
current-context: user2-context
kind: Config
users:
- name: user2
  user:
    client-certificate: path to .crt
    client-key: path to .key