apiVersion: rbac.authorization.k8s.io/v1
kind: Role 
metadata: 
  namespace: development 
  name: user1-role

rules:
- apiGroups: ["", "apps", "networking.k8s.io"]
  resources: ["pods", "deployments", "replicasets", "nodes", "ingress", "services"]
  verbs: ["get", "update", "list", "create", "delete"]


--- 

apiVersion: rbac.authorization.k8s.io/v1
kind: Role 
metadata:
  name: user2-role
  namespace: production 

rules:
- apiGroups: ["", "apps", "networking.k8s.io"]
  resources: ["pods", "deployments", "replicasets", "nodes", "ingress", "services"]
  verbs: ["get", "update", "list", "create", "delete"]



