apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: troubleshooting-daemonset
  labels:
    app: troubleshooting
spec:
  selector:
    matchLabels:
      app: troubleshooting
  template:
    metadata:
      labels:
        app: troubleshooting
    spec:
      containers:
      - name: troubleshooting
        image: kiran2361993/troubleshootingtools:v1
        volumeMounts:
        - name: containerdsock
          mountPath: "/run/containerd/containerd.sock"
      volumes:
      - name: containerdsock
        hostPath:
          path: /run/containerd/containerd.sock

