
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo-deployment
  name: mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-deployment
  template:
    metadata:
      labels:
        app: mongo-deployment
    spec:
      containers:
      - image: mongo
        name: mongodb
        imagePullPolicy: Always
        volumeMounts:
          - name: mongodb-data1
            mountPath: /data/db1
          - name: mongodb-data2
            mountPath: /tmp/db2
          - name: mongodb-data3
            mountPath: /tmp/db3
          - name: mongodb-data4 
            mountPath: /tmp/db4 
      
      volumes: 
        - name: mongodb-data1 
          persistentVolumeClaim: 
            claimName:  task-pv-claim1
        - name: mongodb-data2
          persistentVolumeClaim:
            claimName: task-pv-claim2
        - name: mongodb-data3
          persistentVolumeClaim:
            claimName: task-pv-claim3
        - name: mongodb-data4
          persistentVolumeClaim:
            claimName: task-pv-claim4
      nodeSelector:
        kubernetes.io/hostname: i-017b1e3b65de60447

